language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - node
git:
  depth: 3
script:
  - yarn build
notifications:
  slack: jesusprojects:lSNskQo9LS4erXsBudiejeEH
    rooms:
      
  email:
    recipients:
      - 15-10345@usb.ve
      - gsusqdavid@gmail.com
      - jedave.co@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  edge: true
  skip-cleanup : true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: main